Repository ro-2020/ev3, pull requests merged in 2019-07, with the labels that each got.

#54 青検知の精度向上
  workspace/RO2020EV3/include/Detect.h
  workspace/RO2020EV3/include/Drive.h
  workspace/RO2020EV3/src/Middleware/Detect/Detect.cpp
Labels: area/ミドルウェア, kind/機能

#76 Child feat/#41/look up
  README.md
  build.sh
  workspace/.vscode/c_cpp_properties.json
  workspace/.vscode/settings.json
  workspace/RO2020EV3/.vscode/settings.json
  workspace/RO2020EV3/Makefile.inc
  workspace/RO2020EV3/app.cfg
  workspace/RO2020EV3/app.cpp
  workspace/RO2020EV3/app.h
  workspace/RO2020EV3/include/Config.h
  workspace/RO2020EV3/src/Lookup/Debug.h
  workspace/RO2020EV3/src/Lookup/EmergencyControl.cpp
  workspace/RO2020EV3/src/Lookup/EmergencyControl.h
  workspace/RO2020EV3/src/Lookup/LookUpTest.cpp
  workspace/RO2020EV3/src/Lookup/LookUpTest.h
  workspace/RO2020EV3/src/Lookup/LookupScene.cpp
  workspace/RO2020EV3/src/Lookup/LookupScene.h
  workspace/RO2020EV3/src/Lookup/MasterControl.cpp
  workspace/RO2020EV3/src/Lookup/MasterControl.h
  workspace/RO2020EV3/src/Lookup/MotorControl.cpp
  workspace/RO2020EV3/src/Lookup/MotorControl.h
  workspace/RO2020EV3/src/Lookup/Phase1.cpp
  workspace/RO2020EV3/src/Lookup/Phase1.h
  workspace/RO2020EV3/src/Lookup/Phase2.cpp
  workspace/RO2020EV3/src/Lookup/Phase2.h
  workspace/RO2020EV3/src/Lookup/Phase3.cpp
  workspace/RO2020EV3/src/Lookup/Phase3.h
  workspace/RO2020EV3/src/Lookup/SonarControl.cpp
  workspace/RO2020EV3/src/Lookup/SonarControl.h
  workspace/RO2020EV3/src/Lookup/SonarFilter.cpp
  workspace/RO2020EV3/src/Lookup/SonarFilter.h
  workspace/RO2020EV3/src/Lookup/TailControl.cpp
  workspace/RO2020EV3/src/Lookup/TailControl.h
  workspace/RO2020EV3/src/Lookup/TestData.h
  workspace/RO2020EV3/src/Middleware/Drive/LineTraceDrive.cpp
Labels: area/ルックアップゲート, kind/機能

#80 Phase2の振る舞い向上
  workspace/RO2020EV3/src/Lookup/MotorControl.cpp
  workspace/RO2020EV3/src/Lookup/MotorControl.h
  workspace/RO2020EV3/src/Lookup/Phase2.cpp
  workspace/RO2020EV3/src/Lookup/SonarControl.h
  workspace/RO2020EV3/src/Lookup/SonarFilter.cpp
  workspace/RO2020EV3/src/Lookup/TailControl.cpp
  workspace/RO2020EV3/src/Lookup/TailControl.h
Labels: area/ルックアップゲート, kind/機能

#79 Child feat/#43/start dash
  workspace/RO2020EV3/src/LineTrace/StartDash.cpp
  workspace/RO2020EV3/src/LineTrace/StartDash.h
Labels: area/ライントレース, kind/機能

#78 Child feat/#43/run
  workspace/RO2020EV3/src/LineTrace/Run.cpp
  workspace/RO2020EV3/src/LineTrace/Run.h
Labels: area/ライントレース, kind/機能

#77 Child feat/#43/standby
  workspace/RO2020EV3/src/LineTrace/Standby.cpp
  workspace/RO2020EV3/src/LineTrace/Standby.h
Labels: area/ライントレース, kind/機能

#68 Child feat/#43/line trace unit
  README.md
  build.sh
  workspace/RO2020EV3/Makefile.inc
  workspace/RO2020EV3/app.cfg
  workspace/RO2020EV3/include/Detect.h
  workspace/RO2020EV3/include/Drive.h
  workspace/RO2020EV3/src/LineTrace/ColorDetection.cpp
  workspace/RO2020EV3/src/LineTrace/ColorDetection.h
  workspace/RO2020EV3/src/LineTrace/ColorDetectionTest.cpp
  workspace/RO2020EV3/src/LineTrace/DistanceMeasure.cpp
  workspace/RO2020EV3/src/LineTrace/DistanceMeasure.h
  workspace/RO2020EV3/src/LineTrace/DistanceMeasureTest.cpp
  workspace/RO2020EV3/src/LineTrace/LineTrace.cpp
  workspace/RO2020EV3/src/LineTrace/LineTrace.h
  workspace/RO2020EV3/src/LineTrace/LineTraceScene.cpp
  workspace/RO2020EV3/src/LineTrace/LineTraceTest.cpp
  workspace/RO2020EV3/src/LineTrace/LinetraceMoc.cpp
  workspace/RO2020EV3/src/LineTrace/LinetraceMoc.h
  workspace/RO2020EV3/src/LineTrace/MapStateControl.cpp
  workspace/RO2020EV3/src/LineTrace/MapStateControl.h
  workspace/RO2020EV3/src/LineTrace/MapStateControlTest.cpp
  workspace/RO2020EV3/src/LineTrace/MapStateDefinition.h
  workspace/RO2020EV3/src/Middleware/Detect/Detect.cpp
Labels: area/ライントレース, kind/機能
